version: "3.4"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./../twig_extension/:/var/www
    env_file:
      - ./../.env

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../twig_extension/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
